remote_theme: chrisrhymes/bulma-clean-theme@v0.14.0

lang: en
title: Fortress64
description: Securing Your Digital Privacy.
baseurl: "/"
url: "https://fortress64.github.io/"
permalink: pretty

fixed_navbar: top
theme_color: '#dddddd'
force_theme: light

collections:
  products: 
    output: true
    layout: product
  
social:
  threads: https://www.threads.net/
  youtube: https://www.youtube.com/@Fortress64
