remote_theme: chrisrhymes/bulma-clean-theme@v0.14.0

lang: en
title: Fortress64
description: Securing Your Digital Privacy.
url: "https://fortress64.github.io/"
permalink: pretty

fixed_navbar: top
force_theme: light

social:
  threads: https://www.threads.net/
  youtube: https://www.youtube.com/@Fortress64

footer_menu: footer_menu
