remote_theme: chrisrhymes/bulma-clean-theme@v0.14.0

lang: en
title: Fortress64
description: Securing Your Digital Privacy.
baseurl: "/"
url: "https://fortress64.github.io/"
permalink: pretty

fixed_navbar: top
theme_color: '#dddddd'
force_theme: light
  
social:
  threads: https://www.threads.net/
  youtube: https://www.youtube.com/@Fortress64

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Palatinux Maximus"
      layout: post
      image: https://picsum.photos/id/16/800/600
      show_sidebar: false
